# Generated by Django 4.2.21 on 2025-06-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
