# Generated by Django 4.2.21 on 2025-05-24 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('payment_method', models.PositiveSmallIntegerField(choices=[(1, 'BNI Virtual Account'), (2, 'BCA Virtual Account')])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Success'), (3, 'Failed'), (4, 'Cancel')])),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('settlement_date', models.DateTimeField(blank=True, null=True)),
                ('virtual_account', models.CharField(blank=True, max_length=100, null=True)),
                ('order_destination', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
